name: Run VSCode Extension Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [18, 20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install

      - name: Compile
        run: npm run compile

      - name: Run tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'

      - name: Run tests
        run: npm test
        if: runner.os != 'Linux'
